ccflags-y += -Idrivers/soc/hisense/include

obj-y += hs_devbase.o
hs_devbase-y                          := productinfo.o his_debug_base.o
obj-$(CONFIG_HISENSE_DEBUG_CTRL)      += bootinfo.o his_debug_attrs.o
